### ISSUE TITLE
Clock's Stop button not working in Pluto v0.12.3

### ISSUE THREAD

**Issue by dcurrie** [fonsp/PlutoUI.jl#57]
Running the PlutoUI demo, you can see the Stop buttons for both Clock() examples are not working.

This problem may be related to [this Pluto issue](https://github.com/fonsp/Pluto.jl/issues/570)

I am seeing the same issue in my custom HTML & JS code, which contains buttons that don't seem to get their click events.

Platform: macOS, Julia 1.5.2, latest release Chrome & Safari both

**Comment by dcurrie** [comment]
The Move button issue fonsp/Pluto.jl#570 is a red herring, but my button problem remains and may be the same as the issue with the Stop button in the Clock() examples. Note that the Speed setting in those cells seems broken, too.

**Comment by fonsp** [comment]
I can't reproduce this issue. Is the following button also broken for you?

```julia
# ╔═╡ 121c1a04-0e6d-11eb-0689-f5b6ffe38c48
@bind a html"<button>huh</button"

# ╔═╡ 1c69851e-0e6d-11eb-34d2-fb19c7ca9dba
let
	a
	rand()
end
```

(Copy-paste this text onto a notebook to add them)

**Comment by fonsp** [comment]
Aha! The stop button was broken because the entire clock was broken on PlutoUI `0.6.6` with Pluto `0.12.0`. This was fixed in PlutoUI `0.6.7`. The PlutoUI example notebook still uses 0.6.6, which I have fixed now.

Your custom buttons might be broken because they use `this.querySelector`. This is deprecated in Pluto `0.12.0`, you now use `document.querySelector` to select globally, or `currentScript.closest("pluto-output").querySelector` to select within the current cell.

**Comment by dcurrie** [comment]
> Your custom buttons might be broken because they use this.querySelector. This is deprecated in Pluto 0.12.0, you now use document.querySelector to select globally, or currentScript.closest("pluto-output").querySelector to select within the current cell.

I was using `this.querySelector`, but switching to `document.querySelector` didn't fix it, nor did `currentScript.closest("pluto-output").querySelector` -- I will have to learn how to debug JS I guess.

**Comment by dcurrie** [comment]
OK, I found it... using `document.querySelector` did indeed fix it. Thanks!

**Comment by fonsp** [comment]
>  I will have to learn how to debug JS I guess

Use the developer console! F12, Cmd+Shift+J, something like that
